services:

  migrate:
    image: migrate/migrate:latest
    entrypoint: ["migrate"]
    volumes:
      - ./migrations:/migrations
    depends_on:
      auth_service_mysql:
        condition: service_healthy

  auth_service_app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: auth_service_app
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .env
    depends_on:
      auth_service_mysql:
        condition: service_healthy

  auth_service_mysql:
    image: mysql:latest
    container_name: auth_service_mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: local_dev_db
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpassword
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-plocalpassword"]
      interval: 3s
      timeout: 5s
      retries: 10


  migrate_test:
    image: migrate/migrate:latest
    entrypoint: ["migrate"]
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "mysql://testuser:testpassword@tcp(auth_service_mysql_test:3306)/local_dev_test_db", "up"]
    depends_on:
      auth_service_mysql_test:
        condition: service_healthy

  auth_service_app_test:
    container_name: auth_service_app_test
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./mount:/mount
    working_dir: /app
    env_file:
      - .env.test
    depends_on:
      auth_service_mysql_test:
        condition: service_healthy

  auth_service_mysql_test:
    image: mysql:latest
    container_name: auth_service_mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: local_dev_test_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "127.0.0.1:3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-ptestpassword"]
      interval: 3s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
