version: '3.8'

services:
  auth_service_app:
    build:
      context: .
      dockerfile: docker/auth_service/Dockerfile
    container_name: auth_service_app
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      auth_service_mysql:
        condition: service_healthy

  auth_service_mysql:
    image: mysql:latest
    container_name: auth_service_mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: local_dev_db
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpassword
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-plocalpassword"]
      interval: 3s
      timeout: 5s
      retries: 10

  auth_service_mysql_test:
    image: mysql:latest
    container_name: auth_service_mysql_test
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: local_dev_test_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword

volumes:
  mysql_data:
